#!/usr/bin/env bash

# Factors for converting days, hours and minutes into seconds
DAYS=(24*60*60)
HOURS=(60*60)
MINUTES=(60)
PROGNAME=$(basename $0)

usage() {
  echo "$PROGNAME: usage: $PROGNAME nD nH nM nS"
  echo "where n is a positive number and"
  echo "D = Days"
  echo "H = Hours"
  echo "M = Minutes"
  echo "S = Seconds"
}

to_seconds() {
  local time=0
  a=("$@")
  for t in "${a[@]}"; do
    local unit=$(echo $t | grep -oP '((?<=\d)\D+)')
    case $unit in
      d|D) (( time += $(echo $t | grep -oPi '(\d+(?=d))') * DAYS ))
         ;;
      h|H) (( time += $(echo $t | grep -oPi '(\d+(?=h))') * HOURS ))
        ;;
      m|M) (( time += $(echo $t | grep -oPi '(\d+(?=m))') * MINUTES ))
        ;;
      s|S) (( time += $(echo $t | grep -oPi '(\d+(?=s))') ))
        ;;
      *)   echo "Unknown time unit $unit" >&2; usage; exit 1
        ;;
    esac
  done
  echo $time
}

if [[ -z $@ ]]; then usage; exit 1; fi

to_seconds "$@"

